### ISSUE TITLE
[1.16.5 Forge] Render for Armor breaks when in “Combat” Mode with epic fight’s custom player model

### ISSUE THREAD

**Issue by Shibva** [AzureDoom/MCDoom#10]
According to what I understand the dev of Epic Fight has made a post about how this render issue and can be found being made reference to another post about "3D model glitches" and how to possay correct these render issues with their custom player model

Love this mod and I hope this issue can be fixed, it would look rad to use the doom armors in this mod when fighting the beasts of the nether

**Comment by Shibva** [comment]
Link to see issue where info on how to fix on mods end can be located

https://github.com/Yesssssman/epicfightmod/issues/536

**Comment by AzureDoom** [comment]
I'm sorry but I will not be adding compact to Epic Fights custom armor. I only support the vanilla player model.

**Comment by Shibva** [comment]
Understandable. If is possible would you allow for it to be done on their end if they desire todo such?

**Comment by AzureDoom** [comment]
Of course, the issue will be with any Geckolib powered armor. They will need to account for them.

**Comment by Shibva** [comment]
While this is understandable, would you be willing to add this if someone were to provide you with the custom texture or something that would account for this? 

The dev on their end doesn't want to press this but it's a shame that this rad looking armor can't be used in epic fight without it rendering as broken

In a way maybe an additional part can be made when epic fight is present, because now that I think of it, this mod (epic fight) could allow for more Doom concepts like the glory shot (or whatever that one thing is when you tear a hostile up in doom 2016) while animating the model can be work, I believe that this mod combined with epic fight movement animations on their custom model will go hand and hand in making the overall experience better

Think about it and you might change your mind, but if you don't then that's fine

This is a great mod despite the pain of dealing with the sniper chainguners XD
