### ISSUE TITLE
reroll loot table looping bug 1.20.1

### ISSUE THREAD

**Issue by WilliamBlaze** [AzureDoom/MCDoom#105]
the following bug occurs in the mod pack I'm developing whenever i have AzureLib and McDoom enabled in the mod pack and I'm unable to stop this bug from occurring other then to simply disable azurelib-forge-1.20.1-1.0.18.jar & MCDoom-Forge-1.20.1-6.0.3.jar

I've even tried using earlier versions of these mods since the bug is fairly new in my testing of the mod pack I'm developing, but it still occurred.

Then tried earlier versions of forge for 1.20.1 in hopes of ridding myself of the bug, thinking that might be the solution to fix the tick loop occurring from with these mods, but with no such luck. I'm at a loss, and my own testing concludes there's either a bug or a mod conflict somewhere involving AzureLib & McDoom for 1.20.1

The crash log is a fairly Lengthy one, possibly longer then the character limit for a single post here on Github, so i've pasted the details to my paste bin post on the following link https://pastebin.com/9b8EUPeX

**Comment by AzureDoom** [comment]
Can you try the pack wihtout the mod Improvable Skills 3 as a test? It looks to be the issue here.

**Comment by Xplodin** [comment]
not sure if its the same but im finding this similar.
When I open a chest I crashed with this: https://gist.github.com/Xplodin/e82b393664cae359cebcd0ec34fd6871

**Comment by AzureDoom** [comment]
Sadly this looks to be a forge issue, as it's now conflicting with PNCDungeonLootModifier pneumaticcraft

**Comment by WilliamBlaze** [comment]
After much trial and error - i found a stable version of forge where both mods work without conflicts!
Forge build version 47.1.3 seems to "fix" the issue - as the bug has stopped happening in the mod pack with both sets of mods running together, not sure what was changed or removed from 47.1.16 - finding it odd that the problem solved itself by rolling back to an earlier build but sometimes it do be like that when dealing with forge. 

It's still good to keep note of this though for future users who might bump into this problem when running McDoom on 1.20.1

At any rate hopefully knowing a version where the two mods run stable in the same space helps to narrow down whatever Forge changed in later versions that cause this hiccup.

**Comment by AzureDoom** [comment]
> After much trial and error - i found a stable version of forge where both mods work without conflicts! Forge build version 47.1.3 seems to "fix" the issue - as the bug has stopped happening in the mod pack with both sets of mods running together, not sure what was changed or removed from 47.1.16 - finding it odd that the problem solved itself by rolling back to an earlier build but sometimes it do be like that when dealing with forge.
> 
> It's still good to keep note of this though for future users who might bump into this problem when running McDoom on 1.20.1
> 
> At any rate hopefully knowing a version where the two mods run stable in the same space helps to narrow down whatever Forge changed in later versions that cause this hiccup.

Makes sense since that is when the maintainers all left Forge to make NeoForge as well. I wouldn't recommend updating past 47.1.3 until NeoForge releases as Lex has been merging anything and everything of late with no care for breaking mods.

**Comment by WilliamBlaze** [comment]
nvm, it just changed the trigger state of the bug from crashing at start up to crashing when opening chests. I didn't notice it sooner because i was opening an already existing world, but the moment new loot had to be generated for a chest, there it was, back again.

Seriously I'm stumped how forge screwed the pooch on the mixins responsible for the loot table generation and why its causing Azure Lib to infinitely reroll for the loot tables until the game crashes.

I don't suppose there's a way to kill the reroll process after a set number -say maybe 12 failed attempts- is there?
Because at this point that's about the only solution for newer versions of Azure Lib & McDoom to work with forge going forward given the nature of this bug and whatever it is that forge mucked up in for Minecraft 1.20.1 version(s)'s Mixin(s). - Ya know they're mistake is a big one when even forge's "recommended stable version" is busting your mods, humor aside though.

For now I'll just keep rolling back to earlier versions of Azure lib and McDoom until I either find a combination of the two that work successfully on forge, or until there's no other combinations of those two left for 1.20.1 versions of Minecraft that I can use.

I'll be back to let ya know whether that process leads to any success or if it's been busted.

**Comment by AzureDoom** [comment]
> nvm, it just changed the trigger state of the bug from crashing at start up to crashing when opening chests. I didn't notice it sooner because i was opening an already existing world, but the moment new loot had to be generated for a chest, there it was, back again.
> 
> Seriously I'm stumped how forge screwed the pooch on the mixins responsible for the loot table generation and why its causing Azure Lib to infinitely reroll for the loot tables until the game crashes.
> 
> I don't suppose there's a way to kill the reroll process after a set number -say maybe 12 failed attempts- is there? Because at this point that's about the only solution for newer versions of Azure Lib & McDoom to work with forge going forward given the nature of this bug and whatever it is that forge mucked up in for Minecraft 1.20.1 version(s)'s Mixin(s). - Ya know they're mistake is a big one when even forge's "recommended stable version" is busting your mods, humor aside though.
> 
> For now I'll just keep rolling back to earlier versions of Azure lib and McDoom until I either find a combination of the two that work successfully on forge, or until there's no other combinations of those two left for 1.20.1 versions of Minecraft that I can use.
> 
> I'll be back to let ya know whether that process leads to any success or if it's been busted.

I will longer be supporting 1.20.1 Forge and will be moving 1.20.1 to NeoForge https://neoforged.net/news/theproject/

**Comment by WilliamBlaze** [comment]
Alright thats fine, i did discover that it was from azurelib-forge-1.20.1-1.0.17.jar and onward that the issues started. azurelib-forge-1.20.1-1.0.16.jar and prior work without conflict. -Just making Note of this for anyone else who's still using what will be dubbed "Old Forge"

More importantly though, thank you for this info! I wouldn't have known about Neoforge for a long while without you telling me this.

**Comment by AzureDoom** [comment]
This update is released now!
