### ISSUE TITLE
Crash Server when someone open Chest in Natural Nether Portal

### ISSUE THREAD

**Issue by STARK055** [AzureDoom/MCDoom#107]
Crash Server when someone open Chest in Natural Nether Portal
[crash-2023-07-21_20.51.51-server.txt](https://github.com/AzureDoom/MCDoom/files/12135319/crash-2023-07-21_20.51.51-server.txt)

**Comment by AzureDoom** [comment]
Use 47.1.3. Newer isn't supported due forges stupid ass changes and this mod will be shifted to neoforge instead

**Comment by Xplodin** [comment]
just crashed on 47.1.3....

**Comment by STARK055** [comment]
so i need to change the forge version of the server?

**Comment by AzureDoom** [comment]
> just crashed on 47.1.3....



> so i need to change the forge version of the server?

I will longer be supporting 1.20.1 Forge and will be moving 1.20.1 to NeoForge https://neoforged.net/news/theproject/

**Comment by STARK055** [comment]
Ok, thank you very much for answering. Your mod is super cool. Thank you very much for your work

**Comment by AzureDoom** [comment]
This update is released now!
