### ISSUE TITLE
[1.20.1 Forge Server] Crash upon opening chest

### ISSUE THREAD

**Issue by MrKashew** [AzureDoom/MCDoom#111]
[crash-2023-08-20_17.26.26-server.txt](https://github.com/AzureDoom/MCDoom/files/12389972/crash-2023-08-20_17.26.26-server.txt)

**Comment by AzureDoom** [comment]
Will be fixed with next update but i will be only supporting NeoForge so support for normal Forge is based on NeoForge.

**Comment by AzureDoom** [comment]
This update is released now!
