### ISSUE TITLE
Chests

### ISSUE THREAD

**Issue by SamusMiner** [AzureDoom/MCDoom#112]
In the current version of 1.20.2 chests will automatically crash the game

**Comment by AzureDoom** [comment]
This will be fixed in the next update, but no ETA as I'm currently in the middle of an animation update and a new dim that prevents it from releasing at this time.

**Comment by AzureDoom** [comment]
A workaround is to use Trinkets and the Fabric version via Connector (you want the Forge SmartBrainLib) to load that version, which has working chests.

**Comment by SamusMiner** [comment]
Ah oki, thank you, I thoroughly enjoy the mod with out without bugs

**Comment by AzureDoom** [comment]
This update is released now!
