### ISSUE TITLE
Crash when opening loot chest.

### ISSUE THREAD

**Issue by CyaniideDrive** [AzureDoom/MCDoom#113]
When opening loot chests that can contain MCDoom loot, the server crashes.
I've been trying to figure this out for a while and it seems to be too many loot tables being called at once.

[crash-2023-09-17_09.12.43-server.txt](https://github.com/AzureDoom/MCDoom/files/12642502/crash-2023-09-17_09.12.43-server.txt)

**Comment by AzureDoom** [comment]
Known issue, is fixed in dev, but no ETA on release as I am reworking a ton of the animations, and the mod is not in a build-able state currently.

**Comment by AzureDoom** [comment]
This update is released now!
