### ISSUE TITLE
Mobs not moving or attacking

### ISSUE THREAD

**Issue by EvoMods** [AzureDoom/MCDoom#115]
Minecraft 1.20.1
Forge 47.2.1

SmartBrainLib 1.11
AzureLib 1.0.3
Custom Portal API Reforge 1.0.2
Jade 11.6.1
Global Packs 1.16.2
Better Furnaces Reforged 1.1
Architectury 9.1.12
Factory API 2.0
Botarium 2.2.0
Resourceful Lib 2.1.11
Just Enough Items 15.2.0.27
Curios API 5.3.4+1.20.1

When entering the Nether - Mobs don't move nor attack the player, switching between difficulty modes and between creative/survival makes no changes. I'm able to hit the mobs but they don't react - Let me know if theres any other info you need

**Comment by AzureDoom** [comment]
I don't support any Forge version higher than 47.1.3. Please test on that version.
