### ISSUE TITLE
MOBS NOT MOVING / ATTACKING

### ISSUE THREAD

**Issue by QuadyTheDragoness** [AzureDoom/MCDoom#116]
I have changed my forge version to 47.1.3, and the mobs still are not moving. 
Everything works fine, except for the mobs, who just stand still and don't attack. 
You can imagine how this makes this mod unusable, because of the sheer scope of mobs. 
I will give any data you may require.

**Comment by QuadyTheDragoness** [comment]
I tried changing forge version, i tried neoforge version of the mod, i tried everything, and on 1.20.1, the mobs do not move. I also didn't backup one of my worlds, and ruined it because of testing. Small setback, but quite annoying. Any fixes at all?

**Comment by QuadyTheDragoness** [comment]
Is there an option to turn off the mobs? I can install a different mob mod this way to replace these broken mobs, that would be a fix too

**Comment by AzureDoom** [comment]
Works fine for me, as I just tested it 
![image](https://github.com/AzureDoom/MCDoom/assets/7415711/108aa7e2-4a9f-4c73-ac40-71af4dd24a1a)
