### ISSUE TITLE
Game crashes while loading mods, seems to be an incompatibility issue with Gigeresque.

### ISSUE THREAD

**Issue by CharybdisSlashCrow** [AzureDoom/MCDoom#117]
Sooo my game keeps crashing when I try loading this with the following mods:
MCDoom and its dependencies (Custom Portal API, Curios, SmartBrainLib, and Azurelib)
Gigeresque and its dependencies (Forgified Fabric API and Sinytra Connector)

Here's what I get when I try loading.
The game crashed whilst initializing game
Error: net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'gigeresque'

Exit Code is -1 and the log is attached below. Also noticed the same crash with your other mods (Aftershock, Arachnids, and Dark Waters) as well. Please fix this if you can!

[crash-2023-10-05_19.02.20-client.txt](https://github.com/AzureDoom/MCDoom/files/12825675/crash-2023-10-05_19.02.20-client.txt)

**Comment by AzureDoom** [comment]
If you are using any connector mods, switch to the Fabric version of MCDoom and remove AzureLib Forge and the portals API reforged mods.

**Comment by AzureDoom** [comment]
This issue is now resolved fully with 1.0.32 of AzureLib and 6.0.6 of MCDoom!
