### ISSUE TITLE
[Fabric 1.20.1] Lost Soul crashes game

### ISSUE THREAD

**Issue by LivingSkeleton11** [AzureDoom/MCDoom#119]
Description of issue:
Whenever a Lost Soul spawns, the game crashes.

Mods in use (all for 1.20.1):
MCDoom 6.0.5a
AzureLib 2.0.4
SmartBrainLib 1.12
Trinkets 3.7.1
FabricAPI 0.90.4

Crash report:
[crash-2023-10-31_17.29.02-client.txt](https://github.com/AzureDoom/MCDoom/files/13221513/crash-2023-10-31_17.29.02-client.txt)

Steps to reproduce:
1. Launch Minecraft with MCDoom and its required dependencies
2. Create new world
3. Spawn a Lost Soul
4. Game crashes

Notes:
I did see a closed issue pertaining to this version (MCDoom 6.0.5a), with the reason for closure being that this version of the mod is no longer supported and the author being told to update. However, this version is the latest version for Fabric as far as I can see (on both Modrinth and CurseForge).

**Comment by AzureDoom** [comment]
6.0.6 is the latest, but this is an issue with AzureLib, which received an update that this needs. I have no ETA when I will release it as I'm currently moving it's Forge version to match the Fabric configuration system.
