### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by Niconoko** [AzureDoom/MCDoom#120]
Crashlog: https://pastebin.com/xgk8cLBX
Boot up the game and crash. *Maow* :3

**Comment by AzureDoom** [comment]
> 1.20.1-47.2.0


I do not support any Forge version that is higher than 47.1.3.

**Comment by Niconoko** [comment]
Oki, so forge v47.1.3 is default one to use with ye mods for now then?

**Comment by AzureDoom** [comment]
For 1.20.1 yes. It's because I target NeoForge now, which on 1.20.1 only supports up to that version. 1.20.2+ will be NeoForge only (besides Fabric)
