### ISSUE TITLE
game crashes on start up

### ISSUE THREAD

**Issue by Ghoulhollow117** [AzureDoom/MCDoom#122]
I've just downloaded the mod a few days go but i'm unable to even start the game without it just crashing here's the crash logs
[crash-2023-11-26_20.44.20-client.txt](https://github.com/AzureDoom/MCDoom/files/13468978/crash-2023-11-26_20.44.20-client.txt)

**Comment by AzureDoom** [comment]
1.19.3 is no longer supported.
