### ISSUE TITLE
E1M1 not playing

### ISSUE THREAD

**Issue by gabetronx** [AzureDoom/MCDoom#124]
So I run a Another Quality Modpack 2 server, and the E1M1 music disk is silent when placed in a jukebox. I can obtain it just fine but placing it just plays nothing. I looked in the config for a solution and didn't find anything. I can provide more information upon request.

Video detailing the bug (1:06)
https://youtu.be/zW0MVk-QNiQ

**Comment by AzureDoom** [comment]
This is a fabric bug that simply hasn't been patched on thier end. Nothing I can do to fix

**Comment by gabetronx** [comment]
Aw man, that's too bad.
