### ISSUE TITLE
Rpg mob crashing my game. 

### ISSUE THREAD

**Issue by killermvp1** [AzureDoom/MCDoom#128]
im runnign alot of mod about 220I haven't seen the the entity that's crashing it as soon as it spawns into a chunk my game has a melt down and lags till crash and out puts this error:

Error: java.lang.ClassCastException: class mod.azure.doom.entities.projectiles.entity.RocketMobEntity cannot be cast to class net.minecraft.world.entity.LivingEntity (mod.azure.doom.entities.projectiles.entity.RocketMobEntity is in module doom@7.0.5 of loader 'TRANSFORMER' @58c80957; net.minecraft.world.entity.LivingEntity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @58c80957)

**Comment by AzureDoom** [comment]
I need the full log

**Comment by killermvp1** [comment]
[2024-01-02-4.log.gz](https://github.com/AzureDoom/MCDoom/files/13812930/2024-01-02-4.log.gz)

**Comment by killermvp1** [comment]
[2024-01-02-4.log.gz](https://github.com/AzureDoom/MCDoom/files/13813076/2024-01-02-4.log.gz)
is this the one or do u need the crash log?

**Comment by AzureDoom** [comment]
The crash log

**Comment by killermvp1** [comment]
[crash-2024-01-02_10.47.35-server.txt](https://github.com/AzureDoom/MCDoom/files/13813100/crash-2024-01-02_10.47.35-server.txt)

**Comment by AzureDoom** [comment]
Will have a fix out likely tomorrow, no full ETA however as it depends how I'm feeling/busy with work.

**Comment by AzureDoom** [comment]
Release pending on CurseForge, released on Modrinth now.
