### ISSUE TITLE
All out war in the Nether

### ISSUE THREAD

**Issue by Gamerbolts** [AzureDoom/MCDoom#129]
Hello!

I have your mod for 1.20.1 Fabric. I was testing my modpack and went into the nether, it was an all out war. The Doom mobs were fighting all the other mobs from my modpack. Is there a way to change this? Or is that just how it is, they will kill anything?

**Comment by AzureDoom** [comment]
It's how they are, they are hostile to all mobs that aren't demons or other demons if damaged by another.

**Comment by Gamerbolts** [comment]
Thought that was the case. Dang won't be able to include it in my modpack then. Or figure out someway to only allow Doom mobs to spawn in the Nether

**Comment by AzureDoom** [comment]
> Thought that was the case. Dang won't be able to include it in my modpack then. Or figure out someway to only allow Doom mobs to spawn in the Nether

Custom datapack via tags here: https://github.com/AzureDoom/MCDoom/tree/1.20.1/common/src/main/resources/data/doom/tags/worldgen/biome for changing doom spawns at all, a lot drop vanilla resources to help with this in-fighting and such.
