### ISSUE TITLE
I have an error from a 1.20.1 server, here's the entire log

### ISSUE THREAD

**Issue by SkillsSoTK** [AzureDoom/MCDoom#131]
I made a java server from the official minecraft 1.20.1 page, I added the mod and its add-ons and due to incompatibility with other mods I couldn't use it, I deleted the mod and its add-ons from the server but when the run.bat was executed it gave me a error and the server does not open. I would like to be able to completely remove the mod and be able to run the server as if nothing had happened. Thanks in advance.

[2024-01-02-1.log](https://github.com/AzureDoom/MCDoom/files/13815086/2024-01-02-1.log)

**Comment by AzureDoom** [comment]
You can't remove a mod that adds dims without breaking things. This is past 1.16+ Vanilla behavior.
