### ISSUE TITLE
I have an error on a server with friends 1.20.1, here's the entire log

### ISSUE THREAD

**Issue by SkillsSoTK** [AzureDoom/MCDoom#132]
Hello, I made a server with friends, I already had several mods, I wanted to add the doom and its plugins, but when I started the run.bat I got an error, I understand that the Oculus could not load correctly but I don't know how to solve it, could you help me? please?
[2024-01-03-1.log](https://github.com/AzureDoom/MCDoom/files/13820493/2024-01-03-1.log)

**Comment by AzureDoom** [comment]
This is not an issue with MCDoom, please report to Oculus (which shouldn't be on the server itself in the first place)
