### ISSUE TITLE
Is the plasma rifle supposed to have particle effects?

### ISSUE THREAD

**Issue by StardustPassingBy** [AzureDoom/MCDoom#133]
Been testing out this mod and the plasma rifle doesn't seem to fire any visible projectiles. The terrain lights up as if there's a projectile there, but besides that there's nothing. Is this normal? The BFG manages to fire a particle effect out just fine.

Playing on 1.20.1 on Forge, version 7.0.6.

**Comment by AzureDoom** [comment]
Yes, it's a known issue. Will be looked at more when I update the mod to 1.20.4
