### ISSUE TITLE
[Bug] (1.16.5) Spawn eggs seem to not be fully interative with other mods

### ISSUE THREAD

**Issue by forgotmypancakes** [AzureDoom/MCDoom#135]
The various doom creature spawn eggs seem to not be fully registered in game (I don't know what that means, that's just the response I got from the dev of Apotheosis). In the apotheosis mod, there's an enchantment called capturing that gives mobs a chance to drop spawn eggs, but none of the doom mobs drop any. I commented on apotheosis's page and got the attached response from the dev. 
![Screenshot 2024-02-28 195938](https://github.com/AzureDoom/MCDoom/assets/149659685/d9c0612b-5dbc-47e7-a722-413255f0c7dd). Is there an easy fix to this?

**Comment by AzureDoom** [comment]
1.16.5 is abandoned
