### ISSUE TITLE
Mobs instantly regen health

### ISSUE THREAD

**Issue by BrickFarmer** [AzureDoom/MCDoom#137]
Whenever I attack undead mobs, they instantly regenerate health. Is there something I am missing in my settings? Game is set to easy, playing the MCDoom modpack on Curseforge. I have tried various weapons, but cannot deal any damage that does not get undone. 

Appreciate any help you can provide.

**Comment by BrickFarmer** [comment]
Found the mod causing the regen.

**Comment by Agilemind108** [comment]
which mod do you delete?

**Comment by AzureDoom** [comment]
> which mod do you delete?

https://www.curseforge.com/minecraft/mc-mods/consecration
