### ISSUE TITLE
Server crashes when entering Nether

### ISSUE THREAD

**Issue by RushanM** [AzureDoom/MCDoom#139]
```
Description: Exception ticking world
java.lang.NoClassDefFoundError: net/minecraftforge/common/util/BrainBuilder
```
I have the tech modpack on NeoForge 1.20.1. Because of the MCDoom mod in the pack, any visit to Nether causes the game to crash or freeze endlessly. This is unfortunate because I would love to see Doom creatures in Nether. Attached two crash reports, one from the server and one from the single player game.
[crash-2024-03-20_17.29.15-server.txt](https://github.com/AzureDoom/MCDoom/files/14681597/crash-2024-03-20_17.29.15-server.txt)
[crash-2024-03-21_06.47.14-server.txt](https://github.com/AzureDoom/MCDoom/files/14681599/crash-2024-03-21_06.47.14-server.txt)

**Comment by AzureDoom** [comment]
```
java.lang.NoClassDefFoundError: net/minecraftforge/common/util/BrainBuilder
	at net.tslat.smartbrainlib.api.core.SmartBrainProvider.makeBrain(SmartBrainProvider.java:88) ~[SmartBrainLib-forge-1.20.1-1.13.jar%23394!/:1.13] {re:classloading}
```
Ensure you have the correct sbl. I build against 1.12 of SBL https://github.com/AzureDoom/MCDoom/blob/1.20.1/gradle.properties#L40
