### ISSUE TITLE
I Can't use the special weapons like the BFG (Console log)

### ISSUE THREAD

**Issue by SarlicHTG** [AzureDoom/MCDoom#147]
I use Legacy Launcher, and i put Better Combat mod with this mod, also i put some mod for optimize Minecraft (like Embiddium, Ferritecore etc.)  (i use the MC Version 1.20.1 with Forge 47.2.32) all the other items and entities work fine, the argents tools also work, But starting from the chainsaw to the last hammer, all those weapons crash the game 

[tl-logger8736260115895731641.txt](https://github.com/user-attachments/files/15812417/tl-logger8736260115895731641.txt)

**Comment by AzureDoom** [comment]
Your launcher and Forge are not supported.

**Comment by SarlicHTG** [comment]
then which are the launchers and versions of forge compatible with MCDoom for MC 1.20.1

**Comment by AzureDoom** [comment]
For 1.20.1 use mod launcher like CurseForge, Modrinth or the vanilla launcher. Forge is not supported past 47.1.3 as I only support NeoForge now.
