### ISSUE TITLE
how do i remove the mod from server?

### ISSUE THREAD

**Issue by ZeroTanatos** [AzureDoom/MCDoom#149]
I would like to remove the mod from my world because I can't use the weapons; it crashes the client constantly. I've tried removing the .jar file, but the server doesn't finish loading and insists on putting the mod's .jar file back. I'm playing on version 1.20.1.

**Comment by AzureDoom** [comment]
You have manually edit the nether and level.dat to remove any references to the doom structures/dim. This is how Minecraft works past 1.16.3+. You can't remove mods that affect world generation and expect it keep the world the same anymore.
