### ISSUE TITLE
Mod crashes on fabric 1.20.1

### ISSUE THREAD

**Issue by kittech0** [AzureDoom/MCDoom#151]
https://mclo.gs/HGsmpj8

**Comment by AzureDoom** [comment]
Download grade AzureLib for now, 1.21 port is in progress and thus no 1.20.1 updates will be pushed at this time.

**Comment by kittech0** [comment]
@AzureDoom also i found that the issue starts from version 2.0.28

**Comment by AzureDoom** [comment]
Yes, this was due to events being rewritten to be fixed in AzureLib, I won't be pushing a fix for this until after the 1.21 update is done.

**Comment by AzureDoom** [comment]
Please update now.
