### ISSUE TITLE
The module loads by forcing the dependency

### ISSUE THREAD

**Issue by shenyx110** [AzureDoom/MCDoom#153]
***ALL INFO MUST BE FILLED IN OR THE ISSUE WILL BE CLOSED AS INVALID***

**Minecraft Info:**
Minecraft Version:1.21.1
Modloader version: 21.1.65 neo
Mod version:8.0.0

**Describe the bug**
The module loads by forcing the dependency
[ "accessories" ](https://modrinth.com/mod/accessories)
instead of the same 
["Curios API Continuation (Curios-based API)"](https://modrinth.com/mod/curios-continuation)
or 
["adorned"](https://www.curseforge.com/minecraft/mc-mods/adorned)

**Comment by AzureDoom** [comment]
Accessories is a hard requirement yes. I won't be supporting the other two
