### ISSUE TITLE
[BUG] switch to curios continuation mod

### ISSUE THREAD

**Issue by VaporeonScripts** [AzureDoom/MCDoom#155]
**Minecraft Info:**
Minecraft Version: 1.21.1
Modloader version: neoforge .83
Mod version: latest

**Describe the bug**
make either curios continuation and accessories optional or switch to curios, as i dont want to use accessories

**Comment by AzureDoom** [comment]
Nope, Accessories is multiloader and I like it's interface more so this will be a hard no thank you. this is my mod and my choices of dependancy mods.
