### ISSUE TITLE
[suggestion] let players fire weapons without slowing them down

### ISSUE THREAD

**Issue by Dyshonored** [AzureDoom/MCDoom#18]
I think this will make combat more mobile and interesting, especially for the plasma gun. In addition, I think the mod would become a bit more similar to the Doom video games it is based on, since you can fire a weapon while moving at full speed in those games.

**Comment by AzureDoom** [comment]
The weapons don't cause any slowness when using as it is.

**Comment by Dyshonored** [comment]
What I mean is that the player move at a much slower speed when **firing** the weapons (ie while keeping the right-click key held down for firing the weapons in a sustained manner). Currently, this is akin to moving while fully drawing a vanilla bow without releasing the arrow. This is more noticeable on low damage weapons with high firing rate such as the Plasma Gun and the Chaingun, since one needs to fire the weapon continuously for dealing meaningful damage.

**Comment by MANUXAL** [comment]
Truly it would improve the mod a lot.
