### ISSUE TITLE
( Suggestion )  Second Hell

### ISSUE THREAD

**Issue by MANUXAL** [AzureDoom/MCDoom#25]
First off, thank you for making this mod, it's amazing.
i would like if the vanilla hell was left untouched and the mod used an alternate portal for the contents in the mod, same would go for the end...
i don't know if you're planning on adding some worldgen features or if that would be out of your scope for the mod, it would complicate things a lot more so i understand if you don't want to apply any of these suggestions.

**Comment by AzureDoom** [comment]
This mod is feature complete and no new features will be coming to it. It has exceeded the goals I had planned and its time to let it sit so I can work on other projects
