### ISSUE TITLE
1.16.5 two bugs regarding trading (gun table) and Shotgun

### ISSUE THREAD

**Issue by SteamDoge9000** [AzureDoom/MCDoom#27]
Bug 1

![image](https://user-images.githubusercontent.com/38770780/144950950-23606ee7-107e-4da1-b6e5-ce4033e3ed7f.png)

Bug 2: for some unkown reason after an update wtihin the last month, the shotgun will not reload when pressing the keybind, however other guns are able to be reloade, dispite having the proper amuniton present

hope that this version is still supported for bug fixes

**Comment by SteamDoge9000** [comment]
another bug that I found, idk if this was done on purpose but I can no longer shift-click (multicraft) multiple argant ingots and doign so will only craft one and be made invalid, this is reversed by taking one of the items out of the slots and putting it back in

**Comment by AzureDoom** [comment]
1) Fixed
2) Fixed
3) Vanilla bug, I can't fix.

**Comment by SteamDoge9000** [comment]
thanks, but the thing is, it wasent an issue before for the third one

**Comment by AzureDoom** [comment]
Argent plates recipes for the anvil have been bug for ages like that, it's a vanilla thing. I know, I played with the 1.16.5 mod in my own modpack.

**Comment by SteamDoge9000** [comment]
its strange that it begame relivant after a recent update though for me, I wonder if its a bug that was cuased by another mod preformance optimizations

**Comment by SteamDoge9000** [comment]
bug 1 was not fully fixed, their is still an error in its crafting that requires the dark lord chestplate to make a dark load chest plate

**Comment by SteamDoge9000** [comment]
> 1) Fixed 
> 
> 2) Fixed
> 
> 3) Vanilla bug, I can't fix.


For 3, I believe the issue is a preformance mod for it dint do this 

Posssble candidates: the fast series (fast workbench and fast furnaces; performant, optifine (was present when this was NOT an issue so unlikely to be the cause) etc...
