### ISSUE TITLE
(unconfirmed bug; 1.16.5 observation) Vanilla mods sometimes dont spawn naturaly

### ISSUE THREAD

**Issue by SteamDoge9000** [AzureDoom/MCDoom#28]
I have made an observation nad have noticed that pigilns and hoglins dont generate in the crimson forrest and I presume this might have todo with the other hostile spawns overididng it, howver as of yesterday I have ran into  rare instance of 2 spawned hoglin's. It will, however continue to spawn vanilla mobs that are in vanilla structures. im not sure if this is supoosed to happen but I figrued id report it to be looked at

hope this helps others that are having this issue as well

**Comment by AzureDoom** [comment]
It's due to the massive amount of entities I add to the spawn list, this isn't a bug, this is normal.

**Comment by SteamDoge9000** [comment]
do you think you can possably fix this?

**Comment by AzureDoom** [comment]
it's not a bug, it's normal. as I said **It's due to the massive amount of entities I add to the spawn list, this isn't a bug, this is normal.**
