### ISSUE TITLE
[Fabric 1.18, 4.0.24] Soul Cube and Daisy's Foot don't work.

### ISSUE THREAD

**Issue by TheRacecar194** [AzureDoom/MCDoom#30]
Playing in a modpack for myself, I acquired a Daisy's Foot and equipped it in its respective slot, however it does not give me the effect it's supposed to give. I thought at first it was strange and didn't particularly mind it until a few days later while I was tweaking the modpack and decided to explore the problem again. Confirming now that not only does Daisy's Foot not work but the Soul Cube also doesn't work. I ran another test without all other mods present and it still persists.

https://streamable.com/p0gupr

**Comment by AzureDoom** [comment]
Correct, I had been waiting on trinkets to port and haven't had time to fix. Will only be fixed for 1.18.1 though

**Comment by AzureDoom** [comment]
Will have an update on this week, holidays and all.

**Comment by AzureDoom** [comment]
Newest version pushed now has support for Trinkets again, enabling these two items to work again.
