### ISSUE TITLE
[Forge 1.18.1 Configs] Cyber Demon spawning at different heart values

### ISSUE THREAD

**Issue by itsdinkd** [AzureDoom/MCDoom#31]
As mentioned in discord today, I went to the Nether and noticed Cyber Demon 2016 did not have the same HP as configured in the common config. 

Cyber Demon 2016 HP is set to 500 in the config, but in game it was showing 300 via JADE. 

Doom version: 4.0.0 
Forge 39.0.22

**Comment by AzureDoom** [comment]
![image](https://user-images.githubusercontent.com/7415711/150660512-173fb183-136a-47aa-b4fe-3d1641da4327.png)
Thanks to the wonderful powers of Forge, Health configs are impossible due to the event that registers entities attributes firing before configs are loaded.

**Comment by itsdinkd** [comment]
Lmfao some how... I'm not even surprised by forge anymore lol. Well thank you for looking into it.

**Comment by AzureDoom** [comment]
@itsdinkd was given a work around for Forges shit config loading system, 4.1.0 has the fix for Health/Melee configs, along with a port of the Fabric changes due to the amount of DMs I was getting about them being ported. Enjoy!
