### ISSUE TITLE
Weapon animation bug

### ISSUE THREAD

**Issue by Gamemaster2022** [AzureDoom/MCDoom#32]
Hello, I've recently added your mod to my fabric 1.17.1 (latest) server And noticed a weird bug. If there Are players who have the same gun in their hand And then one of them shoot, the shooting animation (or reloading animation with shotgun) Will occur to both of these players. It Is quite annoying if you want to play PVP with these weapons. I Hope that I described it enough And that we'll find solution. Thank you

**Comment by AzureDoom** [comment]
1.17.1 is unsupported.
