### ISSUE TITLE
1.18.1 Not working because gecko is not available on 1.18.1 and should be removed as forge dependancy.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [AzureDoom/MCDoom#34]

**Comment by AzureDoom** [comment]
Yes it dumbass, ever try fucking reading?
![image](https://user-images.githubusercontent.com/7415711/152870007-dcec7db5-364f-4c0e-8b38-748e8e285c53.png)

**Comment by P3rf3ctXZer0** [comment]
No it turns out your an idiot who decides placing your downloads in the same slot is smart and expect people to dig. I will not respond to you anymore so long as you are lazily combining forge and fabric mods. Take a play from FTB and separate your mod versions. (One upload for fabric and one for forge.)

**Comment by AzureDoom** [comment]
> 

No you are a dumbass, CurseForge doesn't want separate pages, they made it so pages will host both. FTB is stuck in the past, I am following the system in place by CurseForge themselves, but welcome to the ban list fuck tard
