### ISSUE TITLE
Volume in config file?

### ISSUE THREAD

**Issue by Gamerbolts** [AzureDoom/MCDoom#35]
Hello! I was wondering if you could add the ability to change the volume in the config file. I went into the Nether and there was so many mobs making so much noise. I believe I have singled it out to be MCDoom. But when I went to your config file there was no way to alter the sound. Thank you.

**Comment by AzureDoom** [comment]
Sound is handled by Minecraft itself via the sound settings.

**Comment by AzureDoom** [comment]
Reduced mob sounds by 60% in latest update.
