### ISSUE TITLE
MCDoom not working

### ISSUE THREAD

**Issue by Zygloman** [AzureDoom/MCDoom#36]
I was trying to make a modpack and when I tried to launch it with MCDoom it continuously said invalid player data when trying to join a world, even in single player

**Comment by AzureDoom** [comment]
Log? MC Version? Loader version/Type? This is as helpful shouting into the wind.

**Comment by Zygloman** [comment]
playing on 1.18.1 with forge version 1.18.1-forge-39.0.66. 
[2022-02-17-5.log](https://github.com/AzureDoom/MCDoom/files/8093362/2022-02-17-5.log)
This is the last log before I removed it

**Comment by AzureDoom** [comment]
Thank you, will be fixed in an update here in a few hours. Currently doing a ton of sound related nerfing to the mobs.

**Comment by AzureDoom** [comment]
Update will be live as soon as CurseForge approves the file.
