### ISSUE TITLE
Crash in 1.18 caused by Archvile

### ISSUE THREAD

**Issue by CyaniideDrive** [AzureDoom/MCDoom#37]
Server crashed right after I saw a fireball fill my entire screen.
It crashes again every time it starts and I rejoin it.
[crash-2022-02-19_11.15.32-server.txt](https://github.com/AzureDoom/MCDoom/files/8102003/crash-2022-02-19_11.15.32-server.txt)

**Comment by CyaniideDrive** [comment]
Updated to newest version and still get the crash.
[crash-2022-02-19_11.56.20-server.txt](https://github.com/AzureDoom/MCDoom/files/8102076/crash-2022-02-19_11.56.20-server.txt)

**Comment by AzureDoom** [comment]
```
at com.betterinvisibility.OnPlayerAttack.notifyAttack(OnPlayerAttack.java:20) ~[betterinvisibility-1.18.1-1.0.2.jar%2354!/:1.18.1-1.0.2] {re:classloading}
```
This is a better invisibility issue not a MCDoom one
