### ISSUE TITLE
Your current version of Mcdoom is preventing Single Player worlds from Loading

### ISSUE THREAD

**Issue by ModernGamingWorld** [AzureDoom/MCDoom#4]
![2021-09-14_19 05 32](https://user-images.githubusercontent.com/75923060/133349687-416ad5f8-db99-47e0-8583-5e4e0a172b58.png)

**Comment by AzureDoom** [comment]
Do you have Tropicraft installed? There is an open issue with them: https://github.com/Tropicraft/Tropicraft/issues/414

**Comment by ModernGamingWorld** [comment]
@AzureDoom No I do not, this is happening with my custom Modpack current next version I am working on. If I downgrade to McDoom-1.16.5-4.0.8 then I dont have this issue

**Comment by AzureDoom** [comment]
Then there is another mod causing the issue, please provide a **proper** log. Screenshots like that do and help nothing.

**Comment by ModernGamingWorld** [comment]
[latest.log](https://github.com/AzureDoom/MCDoom/files/7166131/latest.log)
[debug.log](https://github.com/AzureDoom/MCDoom/files/7166133/debug.log)

**Comment by AzureDoom** [comment]
Fixed in latest version
