### ISSUE TITLE
Problem wth load mod in Forge 1.16.5

### ISSUE THREAD

**Issue by ZEkA10000** [AzureDoom/MCDoom#42]
Minecraft 1.16.5
Forge 36.2.22
MCDoom (1.16.5) 4.0.34

**Doom Mod (doom) encountered an error during the load_registries event phase**
java.lang.NoClassDefFoundError:

**Doom Mod (doom) encountered an error during the error event event phase**
java.lang.NullPointerException: Registry Object not present: _doom:icon_wall1_

**Doom Mod (doom) encountered an error during the error event event phase**
java.lang.NullPointerException: Registry Object not present: _doom:icon_wall1_

**Doom Mod (doom) encountered an error during the error event event phase**
java.lang.NoClassDefFoundError:

**Doom Mod (doom) encountered an error during the error event event phase**
java.lang.ExceptionInInitializerError: nul

[latest.log](https://github.com/AzureDoom/MCDoom/files/8400827/latest.log)
l

**Comment by AzureDoom** [comment]
1.16.5 is unsupported and you are missing libraries.
