### ISSUE TITLE
[1.18.2] Invisibility too invisible 

### ISSUE THREAD

**Issue by itsdinkd** [AzureDoom/MCDoom#43]
Getting reports that Gobbers Ring of Stealth is making it so doom mobs cannot see the player, not attacking the player. Is it possible to make it on your end so doom mobs can strike players using this ring?

**Comment by AzureDoom** [comment]
https://github.com/AzureDoom/MCDoom/blob/fabric1.18/src/main/java/mod/azure/doom/entity/ai/goal/DemonAttackGoal.java#L51
This is intended, it's how the Invisible Sphere is allowed to work.
https://github.com/AzureDoom/MCDoom/blob/fabric1.18/src/main/java/mod/azure/doom/item/powerup/InvisibleSphereItem.java#L33

Sadly I can't change that without breaking that item as well.
