### ISSUE TITLE
Funny Gun Table Go BRRR with quark's rotation lock feature

### ISSUE THREAD

**Issue by Shibva** [AzureDoom/MCDoom#45]
this only happens if you have the orientation lock set when you are looking up

![image](https://user-images.githubusercontent.com/38770780/173448802-874d303f-4a3d-4737-ad4a-2fb683ec9478.png)

is it a bug, a pending feature, or is it just a scraped thing?
Idk but im reporting this just to be safe

(sidenote: its me again, remember that bug with the smithing table in 1.16.5 not allowing for more than one argent pate to be made at a time or something; id like to tell you that its not the case in this game version)

**Comment by AzureDoom** [comment]
It's just odd behavior by Minecraft itself is all. Left it in as it doesn't really break anything and more hassle to fix haha
