### ISSUE TITLE
[Bug or Feature] the Crucible and Marauder Axe and their innert stage

### ISSUE THREAD

**Issue by Shibva** [AzureDoom/MCDoom#46]
Are the weapons listed above supposed to become depleted once they have their durability used up? if so then this is not occurring when the crucible and marauders ax break 

if not, then please disregard this issue and leave a message explaining why (because I'm curious and like to know the reason behind it)

**Comment by AzureDoom** [comment]
They reload like guns but use Agrent Blocks

**Comment by Shibva** [comment]
ok, in that case, the weapons are broken

IDK what mod is doing it but it seems that there's no break prevention on the items in question; thus when dealing a hit with 2 durabilities, the item will break and become destroyed

Is this intended, because it seems like its not for the item itself to break apart

**Comment by AzureDoom** [comment]
Sword: That is indeed a bug. 
Axe: Vanilla thing as it's just a super powered Minecraft Axe currently, will likely move to the new system the Crucible and Dark Lord Crucible uses.
