### ISSUE TITLE
[1.16.5][4.0.34] Incompatibility with TerraForge

### ISSUE THREAD

**Issue by Subthy** [AzureDoom/MCDoom#47]
The mod has incompatibility with terraForge or at least I think that. Portal to nether not spawn as a normal structure but in a hole. It only happens when world is generated with TerraForge. Without it the portal will spawn normally and will be placed smooth with the terrain.

![2022-06-14_21 16 36](https://user-images.githubusercontent.com/73344257/173722193-ba297bf1-8c0b-4ab8-84cf-bcf446520865.png)

**Comment by AzureDoom** [comment]
1.16.5 is unsupported
