### ISSUE TITLE
[suggestion] DOOM internal mod difficutly w/example and HoE mode

### ISSUE THREAD

**Issue by Shibva** [AzureDoom/MCDoom#48]
let's be honest, some of the things that are added in the mod are OP and can outclass another thing like other mods' armor progression; why go about it when you can grind for it? Presenting my idea: an internal difficulty system that can change how some aspects of the mod work; they would change various gameplay features such as the recipes, entities' behavior, and whatnot. This came to me as I just saw one of my bug reports being wrapped up and thought I would share the modifications I've been making in making the overpowered doom armor set harder to acquire since it is the best armor; broken even in some areas, but some of these things would be better if in the mod itself rather than some third-user modifications

and what better way to implement the difficulties than to use the classic difficulty selection in the classics, from "I'm too young to die" to the ever infuriating "NIGHTMARE"; thinking of it becoming harder for someone to acquire the resources from this mod; here's an example on my take on NIGHTMARE

on NIGHTMARE; the changes are:
-Argent Plates require netherite ingots to make
-Argent Energy Droprates are reduced to having a chance of dropping
-Argent Energys' burntime is reduced to 100 operations worth
-weapons are more brutal to make (partially due to the increased rarity of acquiring argent
-all mobs have a heavy increase in their stats
-Powerups occurring in loot general nether lootables increase
-Enchanting doom-related gear is now harder; (Want mending on your doomsayer set? good luck getting 60-70 levels per each)
-attacks that light you on fire are now Hellfire (3x the average damage; doesn't last as long but deals the overall damage quicker; fire resistance potions are a must yet only reduce the severity of being lit by hellfire by 2; fire protection slows down the rate done by hellfire and has a chance to extinguish it pre-maturely)
-Zombie soldiers groups now have a chance for 1 to spawn riding a zoglin that is well protected and has a pillager-like lock on (Ie: they won't attack anyone else that attacks them other than players no matter what; like how pillagers don't if they shoot one another)
-Gore Nests occur more often and tend to produce more resilient spawns
 
=CyberDemons, DoomHunters, and Gladiators are now 5x harder with dramatic stat increase and are even more deadly than ever
 -**Strongest attacks can kill you in 4 hits with Enchanted Netherite Armor; 2 hits if you are not careful**. 
  -Reduce spawn rate (except for the gladiator's arena)
   -Drops upon kill are doubled and experience is tripled 
    -**CAN BECOME ENRAGED if taking large amounts of damage from non-doom and Minecraft equipment in a short time** (exceptions can be made via weapon/projectile whitelist); May whatever god[s] have mercy on you if you get one enraged
      --66.6% Damage reduction to ALL damage taken; regardless of type (excluding admin exclusive)
      --Regeneration III as long as it ENRAGED
      --All Attacks have a 10% chance to bypass armor; **RESISTANCE INCLUDED**
      --Attack Rate increases by 2x
      --50% chance for attacks to disable shield and durability taken increased
      --**ALL ATTACKS HAVE A 75% to deal Critical Damage with 200-666 durability points being lost on a random piece of armor AND have a 75% chance to ignore any damage dealt that is above 40 (doom crucibles and marauder ax are an exception)  when HP is under 5% (5% on phase 2 for the Gladiator) [SUPER ENRAGED]**
      --All Drops and XP are multiplied by 5 if you managed to beat the damn thing in its enraged state [a reward well deserved]; Special Challenge Advancement with a block of Netherite and 30 levels worth of XP  if you managed to beat it on the Hard difficulty [Note: it must be on hard for the entire fight; any changes in the difficulty during it will void the attempt]
      
That's just a summary of what I thought, of course, it's just my thoughts on it but feel free to use any of them if you like them 

(and yes ill admit when was supposed to be a few small examples became quite in-depth at the end there)
===================================================

and there's one more setting that can be added that's independent of the mod's internal difficulty system idea; HoE mod:

HoE Mode; when enabled will cause all doom-mod natural spawns that can occur in the nether to now also **SPAWN IN THE OVERWORLD**; making it hell on earth... LITERALLY! 
[if both ideas are considered and worked in your way... then may the gods of the damned rock the player once called home to have mercy on those who play NIGHTMARE on HoE mode and locked the game difficulty on HARD]

**Comment by AzureDoom** [comment]
90% of this can be changed via the configs or use of other mods. This is outside the scope of this mod.
