### ISSUE TITLE
Immediate Crash Without Crash Report, Exit Code: 1

### ISSUE THREAD

**Issue by A-Strange-Person** [AzureDoom/MCDoom#50]
My PC specs are as follows:
CPU: AMD Ryzen 7 2700x
( https://www.amd.com/en/products/cpu/amd-ryzen-7-2700x )
RAM: 4 8gb Sticks of Corsair Vengeance LPX DDR4 DRAM 
( https://www.corsair.com/us/en/Categories/Products/Memory/VENGEANCE-LPX/p/CMK32GX4M4B3200C16 )
GPU: MSI GeForce RTX 2080 Gaming X Trio 
( https://us.msi.com/Graphics-Card/GeForce-RTX-2080-GAMING-X-TRIO )

I'm on Fabric Loader 0/14/8-1.19

I have these files in my mods folder:
MCDoom-Fabric-1.19-4.2.4.jar
geckolib-fabric-1.19-3.1.2.jar
fabric-api-0.56.1+1.19.jar

I've isolated MCDoom as the reason that I get a crash, no crash report, and the message of

"An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience.
This crash may be caused by an invalid Java Runtime configuration. Check any custom configuration settings.
Exit Code: 1"

I have no custom configuration settings.

When I launch Minecraft with only MCDoom removed from the mod folder, the launcher gets past finalizing, cpu usage in task manager climbs to 100% until the game finishes launching and shows up in task manager as an app. CPU usage drops to around 5% on the title screen.

When I launch Minecraft with all three files in my mod folder, the launcher gets past finalizing, cpu usage in task manager climbs to around 40% until the game crashes and gives the message above and nothing else happens. The game never shows up in task manager as an app or background process.

I'm trying to give you as much info as possible since I didn't get a crash report, this is everything I know about the issue right now.

**Comment by AzureDoom** [comment]
You are missing mods. Read the requirements next time
