### ISSUE TITLE
Extreme lag in the nether

### ISSUE THREAD

**Issue by DwertlePlayz** [AzureDoom/MCDoom#52]
I have a moderately beefy computer that runs Minecraft very well. In the current modpack I'm using (euphoric curiosity) I get a solid 200-250fps, but it always dropped to almost none in the nether. this also happened to my other friends who were playing the modpack. WE tried removing mods one at a time and the second we removed mcdoom the lag completely disappeared. It seems to be coming from the mcdoom mobs in the nether.

**Comment by AzureDoom** [comment]
Ensured you are fully updated on 1.18 or 1.19. Ive done all I can via the culling in the latest.

**Comment by DwertlePlayz** [comment]
It is fully updated, sorry for bothering. After testing with other mods it seems to be a rendering issue in the pack because other mods with custom mobs like mythic mounts and endgame bosses are also causing lag. Thanks!
