### ISSUE TITLE
Crashing in the nether

### ISSUE THREAD

**Issue by Richtofhen** [AzureDoom/MCDoom#53]
I'm playing on 1.19, latest fabric and mcdoom versions.

My singleplayer world crashes when I enter the nether with this crash report :

[crash-2022-07-10_08.15.19-server.txt](https://github.com/AzureDoom/MCDoom/files/9078589/crash-2022-07-10_08.15.19-server.txt)

**Comment by AzureDoom** [comment]
```
de.cristelknight999.unstructured.features.Piglin.method_13151(Piglin.java:27)
```
Not mcdoom

**Comment by Richtofhen** [comment]
And what about this
[crash-2022-07-10_09.07.37-client.txt](https://github.com/AzureDoom/MCDoom/files/9078606/crash-2022-07-10_09.07.37-client.txt)

**Comment by AzureDoom** [comment]
That is a bug with whatever mod is using CCA.

**Comment by Richtofhen** [comment]
> That is a bug with whatever mod is using CCA.

What is a CCA ?

**Comment by Richtofhen** [comment]
> ```
> 
> de.cristelknight999.unstructured.features.Piglin.method_13151(Piglin.java:27)
> 
> ```
> 
> Not mcdoom

Could you also tell me what's the problematic mod please? Thanks.
