### ISSUE TITLE
two bug

### ISSUE THREAD

**Issue by 48004800** [AzureDoom/MCDoom#54]
1:In mod（forge1.19-4.2.6）, there is no slot corresponding to the daisy's feet. I have installed other mods that doom mod needs.Soul Cube works fine.

2:Modifying the additional melee attack damage of ICON OF SIN in the second stage through the configuration file is invalid
（forge1.19-4.2.6）
<img width="420" alt="image" src="https://user-images.githubusercontent.com/78255094/178443436-cec2d001-aeb4-42e2-a926-edf898336905.png">

Players can modify the damage of guns in the mod, but not the damage of melee weapons, maybe you can consider this proposal.

**Comment by AzureDoom** [comment]
1) Belt slot in Curios. 
2) Fixed in dev but no new Forge releases until 1.19 gets an RB because fuck Forges rewrites

**Comment by 48004800** [comment]
> 1. Belt slot in Curios.
> 2. Fixed in dev but no new Forge releases until 1.19 gets an RB because fuck Forges rewrites

The problem is that there is no that slot in curios.There is only one slot for Soul Cube.

<img width="709" alt="image" src="https://user-images.githubusercontent.com/78255094/178644632-c66f33aa-c061-4cdd-9edc-1a9c9aff0179.png">

I think it may be that the doom mod does not provide the corresponding code so that the corresponding slot does not appear.

**Comment by AzureDoom** [comment]
That is wrong, please see https://github.com/TheIllusiveC4/Curios/wiki/Frequently-Used-Slots

**Comment by 48004800** [comment]
<img width="277" alt="image" src="https://user-images.githubusercontent.com/78255094/178679818-d63cc283-a4ba-40af-86e4-355c771d1f63.png">
I don't understand how this site is helpful in solving this problem

**Comment by 48004800** [comment]
<img width="254" alt="image" src="https://user-images.githubusercontent.com/78255094/178991716-af8b158f-9961-4e01-85bf-c04e30a79a00.png">
I installed a new mod and it successfully added new slots. It seems to be the problem of doom itself
