### ISSUE TITLE
Minecraft Physics Mod Compatibility Issue

### ISSUE THREAD

**Issue by Bullseye55** [AzureDoom/MCDoom#55]
It seems that MCDoom's mobs have a forced death animation(Fall over+shrinkfade), which is conflicting with Minecraft Physic's dismemberment and other effects on death, to the point of causing crashes if Physics is not disabled on some mobs.

Perhaps a config option to disable the death animations MCDoom has in order to let a mod like Physics take over, Brutal-Doom-style?

**Comment by AzureDoom** [comment]
That mod is incompatible with any Geckolib mod and is required to be fixed on their side
