### ISSUE TITLE
There is an issue with loading this mod on Forge 1.19

### ISSUE THREAD

**Issue by ProjektRhythm** [AzureDoom/MCDoom#56]
When I launch the game, it gives me an exit code of:
The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Registry Object not present: minecraft:empty
Exit Code: -1

Please let me know how to fix this if possible.
Thank you.

**Comment by AzureDoom** [comment]
Forge 1.19 is unmaintained because Forge keeps breaking shit and I'm not touching Forge until they bother to release an RB
