### ISSUE TITLE
[1.18.2] Archvileternal missing config options

### ISSUE THREAD

**Issue by itsdinkd** [AzureDoom/MCDoom#57]
It looks like it isn't in the config for changing spawn rates, hp, and damage

**Comment by itsdinkd** [comment]
also since i'm already here ;D can you add a config option to disable/enable soul cube and daisy foot please :)

**Comment by AzureDoom** [comment]
It is under the normal Archvile settings, they are just variants using the old system. 

I will see about doing it when I do the armor config, which will be after my break as I'm currently not doing much modding due to IRL things.

**Comment by AzureDoom** [comment]
Closing as completed per last release.
