### ISSUE TITLE
1.19 on Forge 41.1.0

### ISSUE THREAD

**Issue by Chococrispii** [AzureDoom/MCDoom#58]
Interesting crash issue that may impact future versions.
"java.lang.NullPointerException: Cannot invoke "java.lang.Comparable.compareTo(Object)" because "pivot" is null" when attempting to change keybinds.

[crash-2022-07-30_23.44.46-client.txt](https://github.com/AzureDoom/MCDoom/files/9228012/crash-2022-07-30_23.44.46-client.txt)

**Comment by AzureDoom** [comment]
1.19 is out of support, only 1.19.1 will be supported moving forward.
