### ISSUE TITLE
Mipmap Levels being set to 1

### ISSUE THREAD

**Issue by TheUselessGoddess** [AzureDoom/MCDoom#6]
MC 1.17.1 Latest version of MCDoom
Texture doom:blocks/jump_boost with size 70x30 limits mip level from 4 to 1

**Comment by AzureDoom** [comment]
It's all versions but eh would require a full remodel so it's one the "I'll get around to it but it's not game breaking" list

**Comment by AzureDoom** [comment]
Closing this as it's now fixed but update won't be out until hopefully later today. Just waiting on a new model/texture to be sent.
