### ISSUE TITLE
Icon of Sin went on vacation

### ISSUE THREAD

**Issue by KuroNecron** [AzureDoom/MCDoom#62]
Greetings.

I am using MCDoom in the context of [Another Quality Modpack 3](https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-3) on a server.

A player on my Server spawned an Icon of Sin (in the Overworld, if that matters), and it just _left_.
No one has an idea where it went, we have searched (including cheaty texpacks etc), and we cant get rid of the boss' health bar at the top of the screen.

/kill @e didnt help, neither did going peaceful.
Any ideas how to get rid of the boss except just unloading the mod?

Also, how does this happen? Why can bosses just _walk away_ from the player summoning them?

On another note, Arch Maykr in the End are just sniping everything + everyone from a kilometre away, and lagging out the end very heavy, is there any way to "fix" that?

**Comment by AzureDoom** [comment]
Is this happening to any Icon? Even if you summon a new one? 

As for the Arch Maykr, can you confirm the version of the mod the modpack is on? Pretty sure I had updated that.

**Comment by KuroNecron** [comment]
We updated ourselves to version MCDoom-1.18.2-4.2.23.jar because of something, i dont remember specifically what it was.

we have not tried to summon another icon, because we thought it useless if it just leaves.


Arch Maykr issues might be modpack-specific, as it is affected by some configchanges (not the newconfig.toml from your mod, afaict) somewhere (1k+ HP, instant respawn, stuff like that), any ideas what that could be?

**Comment by AzureDoom** [comment]
The HP would be the config for sure, that's all dinkd as he's tripled most stats. 

Could you try another with `/summon doom:iconofsin` and see if it leaves? Never seen it vanish before unless another Icon of Sin is already (I have it coded so only 1 Boss can be alive at a time in a large area...... you aren't near the overworld arena are you? It's a structure that spawns at the lowest possible y and is in the Overworld.

**Comment by AzureDoom** [comment]
If this is still an issue on latest, please let me know.
