### ISSUE TITLE
CrashLog

### ISSUE THREAD

**Issue by ardissaps** [AzureDoom/MCDoom#65]
https://mclo.gs/cuXZgEu

**Comment by AzureDoom** [comment]
```
java.lang.NoClassDefFoundError: net/minecraft/item/ItemGroup
```
Looks to be issue with your install.

**Comment by ardissaps** [comment]
> ```
> java.lang.NoClassDefFoundError: net/minecraft/item/ItemGroup
> ```
> 
> Looks to be issue with your install.

How can I fix that?

**Comment by AzureDoom** [comment]
by updating

**Comment by ardissaps** [comment]
thx
