### ISSUE TITLE
Kicked when firing gun

### ISSUE THREAD

**Issue by pc2u** [AzureDoom/MCDoom#66]
Whenever my friends or I play on a LAN world and the host fires a gun it kicks us out of the game with this error. We are using 1.19.1 Forge 42.0.9 

![Capture](https://user-images.githubusercontent.com/78880266/187547852-23ea46f1-0636-423d-a82c-10beeb2b45e3.PNG)

**Comment by AzureDoom** [comment]
Use 1.19.2
