### ISSUE TITLE
A non-existent item ID

### ISSUE THREAD

**Issue by 48004800** [AzureDoom/MCDoom#68]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/78255094/192092950-9d545e14-dc1c-4b3e-be0f-976957790bfa.png">
This item does not exist in the game

**Comment by AzureDoom** [comment]
Doesn't affect anything

**Comment by 48004800** [comment]
> Doesn't affect anything

(axe_marauder_open) exists in the game. Is it possible that it is misspelled?

**Comment by AzureDoom** [comment]
it's an old file, it's fine.
