### ISSUE TITLE
icon_fight advancement inactive

### ISSUE THREAD

**Issue by mactso** [AzureDoom/MCDoom#69]
We had an issue that one player couldn't get the kill_icon advancement ( everyone else got it fine- we even left the area and he couldn't get it.  His stats showed he killed it twice).

But that's not the issue I'm reporting.
When I was granting him the advancement, I noticed the "icon_fight" wasn't firing at all.  You may have simply not written it yet.   If not, then something about the location code isn't working right I guess.

Great mod. Thanks

**Comment by AzureDoom** [comment]
Loader and version please. Advancements have been funky the last few minecraft updates.

**Comment by mactso** [comment]
Forge 40.1.76
MCDoom-Forge-1.18.2-4.2.27.jar

Not a biggy-just thought I'd let you know.

**Comment by AzureDoom** [comment]
Hmm yeah, I am able to grant it myself, are you using anything to change advancements? Have you tried resetting their data in the advancements folder? Might be an issue with their file being broken.

**Comment by mactso** [comment]
I can grant it okay. 

The fight_icon advancement isn't being awarded by the game minecraft.   That's the one based on location.

We are only getting these two advancements for the fight.
summon_icon
kill_icon  (one player had trouble getting this- no idea why but I just granted it to him and we moved on).

**Comment by mactso** [comment]
By the way-- that's a really badass looking mob. 

You might want to give him a ranged attack, or the ability to teleport to players (or summon them to him) (or damage them if they are too far away from him) because people are simply building a cage of ordinary blocks around him before the fight.

**Comment by AzureDoom** [comment]
Good idea, I might grant him the same power I gave the Gladiator, when it starts or ends an attack, it creates an explosion but yeah his attacking does need a good range.

**Comment by mactso** [comment]
The first two fights it summoned doom monsters to help it.  The second two fights it did not.

One fun EQ (Everquest) boss mob mechanism was to summon helpers at set percentages.  so like 75%,50%,25%.   If you killed the boss mob "too fast", you ended with an overwhelming number of helpers.  So you killed it to 75% ... then avoided taking it below 51% until you had mostly cleared the adds.

**Comment by AzureDoom** [comment]
Closing this as it's not reproducible.

I have also updated the Icon of Sin with some anti-cheese measures. See changelog!

**Comment by mactso** [comment]
Awesome.  Looking forward to folks reactions and new strats!
Doesn't seem like a nerf.  Seems like a fair upgrade to keep it from being cheesed!

**Comment by AzureDoom** [comment]
Oh yeah far from nerf, it's a massive buff. He's going to fuck some days up lol

**Comment by mactso** [comment]
Lol.  Our perspectives were reversed.   
I was talking about from the player's point of view.
