### ISSUE TITLE
Add config to disable Villager trades

### ISSUE THREAD

**Issue by FelixR302** [AzureDoom/MCDoom#7]
Some of the villager trades seem bugged or unbalanced and it would be better for modpacks to add a disable option altogether

**Comment by AzureDoom** [comment]
I can add this add at some point but it won't be for some time as I have someone doing an intense bug testing run (hence all the updates of date fixing things)

**Comment by AzureDoom** [comment]
Will be in the next update. I have 4 new config options for it. Disabling All and Disabling Per (Weaponsmith, Toolsmith, and Mason)

**Comment by AzureDoom** [comment]
This has now been pushed and is live!
