### ISSUE TITLE
Option for Argent Tools to require Argent ingots.

### ISSUE THREAD

**Issue by KnightSpartan** [AzureDoom/MCDoom#70]
The Argent tools are very powerful for requiring only killing demons and sticks. It makes the mod hard to include in packs because the Argent tools overshadow all other balanced tools. I'm in the mod files myself trying to figure out how to change the recipe but I have no idea what I'm doing.

**Comment by AzureDoom** [comment]
This is done via a datapack but I do agree about moving them to the main argent type instead of the other kind. Will do in the next update here.

**Comment by KnightSpartan** [comment]
Thanks a lot. Yeah I was just learning how to use datapacks to do it lol.
