### ISSUE TITLE
Tuning Suggestion: Knockback resistance

### ISSUE THREAD

**Issue by mactso** [AzureDoom/MCDoom#72]
After about 10 hours more play, I have a couple more suggestions.

1) You may want to consider giving the larger mobs some knockback resistance (to make them more "weighty" feeling.   Not 100%-- maybe 33%?  Just so they get knock back less than smaller mobs.

2) I think the Maurauder attack animation is a bit too fast so it looks artificial.

3) Several of the giant mobs have problems with ankle-biting setups.  They walk right up next to the player they can't see and die to a series of hits to the ankles when it would make more sense to back away and take pot shots.  This might be very hard to fix but FYI.

4) You may benefit from raising the attribute "follow distance" to 40 once they are hit by a player.   It's possible to attack them from extreme range and they do nothing because they are in player range but appear to not be in their follow range (probably 24...)  Minecraft skeletons have a similar issue.    If you wait to raise it until they are hit, then it won't use a lot of CPU pathfinding but they will engage instead of standing there being killed (killed a mother demon this way).

**Comment by AzureDoom** [comment]
Thanks for the suggestions! I'm currently working on another mod for a while, but I'll keep this open as I do have some WIP changes already, mostly focused around the Gladiator!

**Comment by mactso** [comment]
Suggestion on the Marauder Axe
So we finally got the hafts and made the axes.
1) The 45 damage isn't that much compared to the 25 points much easier to acquire netherite smite 5 swords do.
2) They appeared to be using 2 ammo per hit
3) As a result, the axe is destroyed after three uses unless you reload after 2 uses.  Unlike other ammo items, it doesn't go to 0 and become useless.
4) The four enchantment X are nice and feel like an endgame weapon but are undercut by the low usage.
5) The argent block reload is very good and gives a use for the torrents of argent energy.

So our improvements
1) Prevent the axe from being destroyed at zero ammo.   Just make it not work or perhaps only do 12 points.
2) Increase the damage to about 80 or 100 points.  This will let a person oneshot Summoners and Arch-Viles.
3) Increase the ammo from 6 to 12 ammo (or 24 ammo if it is going to use 2 per hit- basically 12 actual swings).

---

I liked your code for this item. I didn't know I could add enchantments to items that way.
Cheers,
MacTso

**Comment by mactso** [comment]
The Cyber Demon fires 8 missiles and then it stands around while it is being killed.

Argent tools are available for extremely low prices from villagers (and can't be configured or turned off)

**Comment by AzureDoom** [comment]
> Argent tools are available for extremely low prices from villagers (and can't be configured or turned off)

Yes it is, it's under enable_toolsmith_trades trades.

**Comment by AzureDoom** [comment]
> Suggestion on the Marauder Axe So we finally got the hafts and made the axes.
> 
> 1. The 45 damage isn't that much compared to the 25 points much easier to acquire netherite smite 5 swords do.
> 2. They appeared to be using 2 ammo per hit
> 3. As a result, the axe is destroyed after three uses unless you reload after 2 uses.  Unlike other ammo items, it doesn't go to 0 and become useless.
> 4. The four enchantment X are nice and feel like an endgame weapon but are undercut by the low usage.
> 5. The argent block reload is very good and gives a use for the torrents of argent energy.
> 
> So our improvements
> 
> 1. Prevent the axe from being destroyed at zero ammo.   Just make it not work or perhaps only do 12 points.
> 2. Increase the damage to about 80 or 100 points.  This will let a person oneshot Summoners and Arch-Viles.
> 3. Increase the ammo from 6 to 12 ammo (or 24 ammo if it is going to use 2 per hit- basically 12 actual swings).
> 
> I liked your code for this item. I didn't know I could add enchantments to items that way. Cheers, MacTso

I've tweaked the defaults for all 4 power weapons (2 swords, Axe, and Hammer) to all be a max of 23 uses, won't break when empty now, does 0.1 damage until repaired, and Axe got a damage buff (the damage you see on the tool tip is not the actual damage done, this handled post hit code where it does 200 damage now instead of 100)

As for the damage, I am only doing 1 use myself so not sure might be changing it for you but even with Better Combat, it was using 1 damage per hit.

**Comment by AzureDoom** [comment]
> Several of the giant mobs have problems with ankle-biting setups. They walk right up next to the player they can't see and die to a series of hits to the ankles when it would make more sense to back away and take pot shots. This might be very hard to fix but FYI.

> The Cyber Demon fires 8 missiles and then it stands around while it is being killed.

This is all now tweaked and Arch Maykr, Classic Highknight, Baron, Fireborne Baron, Cyberdemons all now Strafe.

I am building this update now and pushing to CurseForge/Modrinth shortly!

**Comment by mactso** [comment]
Woot!  This all sounds great.   Glad I was able to help identify the areas.
I always look at things as both a game master / referee and as a player.  I want it to be challenging but fun.
Pleasure working with you.
Cheers,

**Comment by AzureDoom** [comment]
No problem! If you have any other suggestions, feel reach to reach out! I've been doing buffs to other mobs as well, I have another update pending now that Geckolib is stable again that will fix some strafing issues I found, add strafing to more mobs and increase the speed of others! (Lost Soul for one is getting a nice speed boost to emulate how the Doom 64 Lost Souls work, (low HP but fast and in your face)
