### ISSUE TITLE
Several Questions about Gladiator

### ISSUE THREAD

**Issue by 48004800** [AzureDoom/MCDoom#73]
MC Doom:1.19.2-4.2.18
curios:1.19.2- 5.1.1.0
geckolib: 1.19.2 -3.1.28
One problem is the doom mod itself. When Gladiator is in the second stage, throwing a hammer to attack the target will cause the game to crash.

https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/721
The second problem is related to other mods

The withering storm attacks the Gladiator, causing that Gladiator is not really dead and cannot be killed.

Finally, there is a problem. The Demon Mother and some other entities will explode after using fire attacks. I think the damage of explosion is relatively high. It is reasonable that the explosion damage is 2 to 3 times of the flame.

**Comment by 48004800** [comment]
I don't know if the second question is related to Doom

**Comment by AzureDoom** [comment]
1) Gladiator is rewritten in dev and is different from what you are using. 
2) I can't fix the Wither Storm bug as it's overwriting death stuff I do, that's not on my end to fix. 
3) This is normal.

**Comment by 48004800** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/721#issuecomment-1366134758

**Comment by AzureDoom** [comment]
Test the latest if you haven't. It works for my uses and vanilla so it's not an issue with my mod.

**Comment by 48004800** [comment]
https://www.curseforge.com/minecraft/mc-mods/mcdoom/files/4182748
https://www.curseforge.com/minecraft/mc-mods/crackers-wither-storm-mod/files/4030212
This is the version I use
I don't know if doom 4.3.3 fixes any bugs. I use the latest version of 1.19.2
![2022-12-29_13 11 18](https://user-images.githubusercontent.com/78255094/209906246-b5399562-1035-42e5-8ec3-dedd212dbc53.png)

**Comment by 48004800** [comment]
Only gladiators have this problem in this mod. Other entities perform normally
I think there's something wrong with gladiators

**Comment by AzureDoom** [comment]
1.19.2 is unsupported with 1.19.3 release.
