### ISSUE TITLE
mon can see and attack trough blocks even by long distances 

### ISSUE THREAD

**Issue by alessandriLuca** [AzureDoom/MCDoom#74]
hi, I'm using your mob in the overworld, but they seems to see me and attack me even tough we are on different level (y) and very far away. let's say I'm in the basement of my home and they are on the ground floor and not directly above me but even in distance they can either shoot me or attack me in a weird way like the dread knight do.version 1.18.2

**Comment by AzureDoom** [comment]
The dread knight/hell knight is normal for this
