### ISSUE TITLE
Cacodemon texture glitched

### ISSUE THREAD

**Issue by DanDragonWolf** [AzureDoom/MCDoom#76]
![Minecraft_ 1 19 2 - Singleplayer 11_23_2022 1_24_47 PM](https://user-images.githubusercontent.com/62574409/203629593-4789c6a8-9dc2-4805-86b6-5951a966af2e.png)

**Comment by DanDragonWolf** [comment]
This is on the Fabric version. I haven't checked the other versions.

**Comment by AzureDoom** [comment]
Can you get the data of that cacodemon please? with /data i believe is the vanilla command.

**Comment by DanDragonWolf** [comment]
The type of Cacodemon is Variant 4 in the data

**Comment by DanDragonWolf** [comment]
Also, I can only get Variants 1 and 4 to spawn when I use the spawn egg,

**Comment by AzureDoom** [comment]
Thanks, will look later.

**Comment by AzureDoom** [comment]
Fix for this should be out in a few hours. Was a simply issue of `==` instead of `>=`
