### ISSUE TITLE
[Suggestion] Enhancement for the mod

### ISSUE THREAD

**Issue by TheRealPicasso** [AzureDoom/MCDoom#79]
The weapons should be held by 2 hands in front of the torso in first person and third person to make it look more realistic. Also the mobs apparently don't have a compability with the physics mod (which creates a corpse of the mob after killing), they just dissappear in this case instead of leaving a corpse.

P.s: Pls 1.18.2 update, if not, then at least for newer versions. Very cool mod!

**Comment by AzureDoom** [comment]
1 19.3 is the only supported version.

I use the default player poses for compatibility with other mods and the current pose is the best. Hands are not possible with my setup.

Physics mod is incompatible with Geckolib and not on possible to make compatible.
