### ISSUE TITLE
Demons are not spawning in the nether

### ISSUE THREAD

**Issue by zimbal11** [AzureDoom/MCDoom#80]
while playing minecraft 1.19.3 with the mcdoom mod and others mods as well i noticed that only the vanilla mobs of the nether spawns without any demons from de mcdoom mod, im playing on hard difficulty and using fabric.

**Comment by AzureDoom** [comment]
If you are using mods that change the nether, you must add the new biomes to the config for them to spawn in. They default to the vanilla nether biomes only.

**Comment by zimbal11** [comment]
I disabled every mod except for doom fabric, fabric api, geckolib and trinkets and the demons are still not spawning. Also im using the prism launcher

**Comment by zimbal11** [comment]
I dont have any mods that adds new biomes to the nether
