### ISSUE TITLE
Minecraft 1.19.3 fabric game crash

### ISSUE THREAD

**Issue by zimbal11** [AzureDoom/MCDoom#83]
I updated to mcdoom version 4.3.5 and when a revenant missile hit the ground the game crashes

**Comment by AzureDoom** [comment]
Post an actual crashlog

**Comment by zimbal11** [comment]
https://mclo.gs/6LXEh9W this is the crashlog

**Comment by xtg61901** [comment]
Having the same issue

**Comment by AzureDoom** [comment]
fixed in newest release that's uploading to CF and Modrinth now.
