### ISSUE TITLE
mobs rarity

### ISSUE THREAD

**Issue by Rogenar** [AzureDoom/MCDoom#85]
mobs spawn very rarely and give 1 argent energy even when the sword has loot magic.Also, they do not spawn in fibroids added by the better end and better nether mods.

**Comment by AzureDoom** [comment]
Loot is intended and spawning is something you have to configure for modded biomes

**Comment by Rogenar** [comment]
Will this issue be fixed with the next update?

**Comment by AzureDoom** [comment]
No, there is no issue here. Everything is working as intended and you must manually add modded biomes to the configs for the mobs

**Comment by Rogenar** [comment]
Are there any mods you can give examples?
