### ISSUE TITLE
Can't enchant items in anvil

### ISSUE THREAD

**Issue by AmonWarner** [AzureDoom/MCDoom#88]
You can't enchant the guns and stuff in anvil, but you can in enchant table and /enchant. Is this a bug or a feature?

**Comment by AzureDoom** [comment]
It is intended

**Comment by AmonWarner** [comment]
Then why is mending an optional enchant?

**Comment by AzureDoom** [comment]
Because that's a bug with whatever mod is changing enchanting.

**Comment by AmonWarner** [comment]
Then how do I reload the sword? Or is it just a few time use item?

**Comment by AzureDoom** [comment]
It uses Argent Blocks but reloads the same as guns.
