### ISSUE TITLE
Texture Pixellation

### ISSUE THREAD

**Issue by Dragonfly-Totem** [AzureDoom/MCDoom#89]
One of my players reported that the texture on **E1M1 Block 9** appears massively pixelated on its X- and Z-axis sides when compared to the other E1M1 blocks.

It's not an explicit "error," as in it doesn't make things literally unusable -- It's just a point of possible polish that can be addressed by the team.

**Comment by AzureDoom** [comment]
The textures would need redone as they were gifted by an old resource pack. Not currently worried about it at this time.
