### ISSUE TITLE
Restricting spawning based on distance to nether portal

### ISSUE THREAD

**Issue by ArcusMG** [AzureDoom/MCDoom#9]
Loving the mod so far. I would like to see the option to have tougher mobs spawn much further from the nether portal. I know that may be a lot of work and maybe not even something you’re interested in but I think it could be a cool idea. I know there are some other mods that make mobs tougher the further you are from spawn (giving them more HPs and such), so this would be similar but related to types of Doom mobs.

**Comment by AzureDoom** [comment]
Sadly as good a feature this would be, I am not putting in new systems at this as I have other mods that work and outside some model changes I have planned for this, this mod is feature complete.
