### ISSUE TITLE
[1.16.5] Dread Knight crashing

### ISSUE THREAD

**Issue by Subthy** [AzureDoom/MCDoom#92]
Hello,

I know 1.16.5 is not supported anymore, but Dread Knight is causing crashes and you can't disable it in the config or with In Control mod. I think it is worth fixing it, as this issue is making the mod unplayable in this version.

Here is the crash report:
[crash-2023-04-06_18.23.34-client.txt](https://github.com/AzureDoom/MCDoom/files/11172091/crash-2023-04-06_18.23.34-client.txt)

**Comment by AzureDoom** [comment]
Use https://www.curseforge.com/minecraft/mc-mods/mcdoom-hotfixes

**Comment by Subthy** [comment]
Thanks and sorry to hear that you lost the source code. Looks like you need to do it from scratch for 1.16.5 :)

**Comment by AzureDoom** [comment]
There are no plans to update the 1.16.5 version, so there is no point. That mixin mod is all that's needed
