### ISSUE TITLE
crashes before opening

### ISSUE THREAD

**Issue by GamingLegend0** [AzureDoom/MCDoom#94]
![image](https://github.com/AzureDoom/MCDoom/assets/88462881/26d81d61-459d-4f3e-8ef2-d8efd4580348)
[crash-2023-05-11_23.46.36-client.txt](https://github.com/AzureDoom/MCDoom/files/11458694/crash-2023-05-11_23.46.36-client.txt)
i have no mods installed other than MCDOOM and its requirements

**Comment by AzureDoom** [comment]
`§7java.lang.NoClassDefFoundError: net/tslat/smartbrainlib/api/SmartBrainOwner`
Please review the required libraries marked on the as they are listed on CurseForge.
