### ISSUE TITLE
RuntimeException: Failed to instantiate language adapter: kotlin

### ISSUE THREAD

**Issue by BlueCorallite** [AzureDoom/MCDoom#95]
Hi, I'm getting a crash that (I'm fairly sure) is caused by MCDoom. The game runs fine without MCDoom, but will crash when I try to use it. I am running it with a bunch of other mods, mainly optimization mods and mods that work with Better Combat.

![image](https://github.com/AzureDoom/MCDoom/assets/64111918/54b385bf-6134-4652-9485-d44c19fb75f9)

Would appreciate any help if possible.

**Comment by AzureDoom** [comment]
Please post an actual log

**Comment by BlueCorallite** [comment]
Where exactly do I find that? the crash-reports folder doesn't seem to have it.

**Comment by AzureDoom** [comment]
The mains log folder latest?

**Comment by BlueCorallite** [comment]
[latest.log](https://github.com/AzureDoom/MCDoom/files/11471261/latest.log)

Thanks. Here you go

**Comment by AzureDoom** [comment]
Please update to v.5.0.4HF and update Azurelib as well for this!

**Comment by BlueCorallite** [comment]
Seems to be working, no crash! Thanks a lot!
