### ISSUE TITLE
Chinese translation is garbled

### ISSUE THREAD

**Issue by chrysoljq** [AzureDoom/MCDoom#98]
In lang file https://github.com/AzureDoom/MCDoom/blob/fabric1.19/src/main/resources/assets/doom/lang/zh_cn.json, Chinese translation is garbled like `MC æ¯�ç�­æˆ˜å£«`, but should be `MC 毁灭战士`.

related issue https://github.com/AzureDoom/MCDoom/issues/96

**Comment by AzureDoom** [comment]
Will likely remove it then unless someone wants to pr a fix.
